apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: rodan-demo-v5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rodan-demo-v5 
  name: rodan-demo-v5
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rodan-demo-v5
    weight: 100 
